# Generated by Django 3.2.5 on 2022-07-06 13:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.SlugField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='43 words 303 characters', null=True)),
                ('service_simble', models.ImageField(default='default.png', help_text='124 x 124 pixels', upload_to='services_simble')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slider_image', models.ImageField(default='default.png', help_text='2400 x 750 pixels', upload_to='services_slider_images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotosRetouchService.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('before_image', models.ImageField(default='default.png', help_text='460 x 600 pixels', upload_to='portfolio_images')),
                ('after_image', models.ImageField(default='default.png', help_text='460 x 600 pixels', upload_to='portfolio_images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotosRetouchService.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGallerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.png', help_text='770 x 432 pixels', upload_to='services_gallery_images')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotosRetouchService.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price_form', models.FloatField(default=0.0)),
                ('price_to', models.FloatField(default=0.0)),
                ('pricing_image', models.ImageField(default='default.png', help_text='600 x 320 pixels, before and after image', upload_to='pricing_images')),
                ('work_process', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotosRetouchService.service')),
            ],
        ),
    ]
