# Generated by Django 3.2.5 on 2022-07-05 14:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_picture', models.ImageField(default='default.png', help_text='106 x 106 pixels', upload_to='review_client_pictures')),
                ('review', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('picture', models.ImageField(default='default.png', help_text='270 x 300 pixels', upload_to='team_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('services', models.TextField()),
                ('message', models.TextField(blank=True)),
                ('filelink', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteFormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('images', models.ImageField(default='default.png', upload_to='quote_images')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotosRetouchTheme.quoteform')),
            ],
        ),
    ]
